### ISSUE TITLE
How to install a Mod ?

### ISSUE THREAD

**Issue by T0MuX** [cyrakuse/Modules-Agora#1]
Hi, we just started to deal with Agora Project. We would like to install some of modules availables here, but I don't know to install them into Agora. I have a folder "app" in which all the préinstalled modules are, but the structure in each folder is not the same than the modules available here.
Can you help me please ?
thank you

**Comment by cyrakuse** [comment]
Agora code has changed and the modules need to be adapt to the new versions of Agora

Cyrakuse
Le 14 févr. 2017 09:57, T0MuX <notifications@github.com> a écrit :

Hi, we just started to deal with Agora Project. We would like to install some of modules availables here, but I don't know to install them into Agora. I have a folder "app" in which all the préinstalled modules are, but the structure in each folder is not the same than the modules available here.
Can you help me please ?
thank you

**Comment by T0MuX** [comment]
Okay, have you some informations on this ? on how to adapt de mods to the new code ?

**Comment by arnomas** [comment]
did you find the answer to the question you were asking for T0MuX ?

**Comment by T0MuX** [comment]
Not really. I discovered there is 2 differents structure of agora's addons : one seem to be the old structure, and the another one the new (the actual format agora supports). The addons was interested me are in old format. I never succeed to make them work. :/

**Comment by arnomas** [comment]
Thanks for reply, where did you find the addons of the new structure ? i was thinking that addons era was over on the new agora.

**Comment by T0MuX** [comment]
The addons of the new structure are already in the last release of Agora, you know, it's just included in the package
